services:
  backend:
    build:
      context: ./bookitout-back/bookitout
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  flask:
    build:
      context: ./bookitout-flask/crawler
    ports:
      - "5001:5000"
    command: ["python", "main.py"]
    env_file:
      - ./.env

  frontend:
    build:
      context: ./bookitout-front
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=http://bookitout.site:8000
    env_file:
      - ./.env
    volumes:
      - ./certbot-data/conf:/etc/letsencrypt
      - ./certbot-data/www:/var/www/certbot
    depends_on:
      - backend
      - certbot

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookitout
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "developer", "-p$${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  certbot:
    image: certbot/certbot
    # ports:
    #   - "80:80" # Certbot standalone 모드를 위해 80번 포트 매핑 추가 - 이제 사용하지 않음
    volumes:
      - ./certbot-data/conf:/etc/letsencrypt
      - ./certbot-data/www:/var/www/certbot
    command: tail -f /dev/null

volumes:
  mysql-data:
  redis-data:
  certbot-data:
