server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

secret-key: ${SECRET_KEY}

library:
  api:
    key: ${LIBRARY_API_KEY}

crawler:
  api:
    url: ${CRAWLER_API_URL}